# Generated by Django 5.1.2 on 2024-11-06 15:40

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_test_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(storage=core.storage.MediaStorage, upload_to=''),
        ),
    ]
