# Generated by Django 5.1.2 on 2024-11-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_test_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='weaviate_id',
            field=models.UUIDField(default='34de146e-56b6-4507-abf8-6f4b36995fad'),
            preserve_default=False,
        ),
    ]
